GET http://localhost:3001/api/persons/4
###
GET http://localhost:3001/api/persons/6
###
DELETE http://localhost:3001/api/persons/4
###
POST http://localhost:3001/api/persons/ HTTP/1.1/
content-type: application/json

{
    "name": "Lemuel",
    "number": 12234556
}
###
POST http://localhost:3001/api/persons/ 
