GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/64087f42ee73adfdca7d6f67
###
DELETE http://localhost:3001/api/persons/64087b28ca3ef903ebfbe65c
###
POST http://localhost:3001/api/persons/ HTTP/1.1/
content-type: application/json

{
    "id": 1,
    "name": "Lem",
    "number": 11234323
}
###
POST http://localhost:3001/api/persons/ 
###
POST http://localhost:3001/api/persons/ HTTP/1.1/
content-type: application/json

{
    "name": "Lemuel1"
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1/
content-type: application/json

{
    "number": "124455464"
}